version: '3.9'
services:
  matchmanagementapi:
    image: "darampatzis/matchmanagementwebapp"
    ports:
      - "8080:80"
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "MatchManagementAPI@"
    ports:
      - "1434:1433"